title:            Mohammad A. Jauhar
description:      Notepad
url:              https://majauhar.github.io/
permalink:        /posts/:title
timezone:         Europe/Paris
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: true
  pages:
    output: true
  stories:
    output: true
  papers:
    output: true
    permalink: /papers/:name/

include: [".well-known"]
markdown: kramdown
recent_date: "2026/01/16"

# Additional support for MathJax
enable_math: true
mathjax:
  version: "3.2.0"
