services:
  jekyll:
    image: jekyll-local
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site
